routes/serie.py
#Imports de flask y componentes necesarios
from flask import Blueprint, render_template, request, redirect, url_for, flash
import sqlalchemy
from models.marca import Marca
from models.serie import Serie
from utils.db import db

# Linea enroutador. Para llamarlo desde otras clases
series = Blueprint("series", __name__)


# Método que devuelve la vista de la lista de series 
@series.route("/series/")
def index():
    # Guarda la lista en una variable de lista, y la lleva al template
    series = Serie.query.all()
    # Guarda las marcas porque serán necesarias para crear elementos nuevos
    marcas = Marca.query.all()
    # Función para renderizar el template con las variables que se le envían
    return render_template("series/index.html", series=series, marcas = marcas )

# Método que se ejecuta cuando se guarda una nueva serie en la bbdd
@series.route("/series/new", methods=["POST"])
def add():
    # Con request saca el valor Flask del form del template
    nombre = request.form["nombre"]
    marca_id = request.form["marca_id"]
    # Comprobar si existe ese nombre ya
    # Se comprueba por nombre y por marca
    records = db.session.query(Serie).filter_by(nombre=nombre, marca_id=marca_id).first()
    if records == None:
        if nombre != "":
            # Nuevo objeto para guardar
            new_serie = Serie(nombre)
            # Añadirle a la marca que tenga ese id el elemento de serie
            marca = Marca.query.get(marca_id)
            marca.series.append(new_serie)
            # añadido a la bbdd
            db.session.add(new_serie)
            # Ahora se acaba con la conexión y se hace commit
            db.session.commit()
            # Antes de reenviar, guardamos algo en la funcion flash
            flash("Serie añadido satisfactoriamente!")
            # Función de flask para hacer redirecciones 
        return redirect(url_for('series.index'))       
    # Mensaje de redireccón si ya existe
    flash("Ese elemento ya existe")
    # Redirección al index de series
    return redirect(url_for('series.index'))    

# Método para hacer un update de un elemento.
# Acepta los métodos de GET para llevar a la viste del update con el objeto,
# También el método POST cuando se haya ejecutado la opción de update del formulario.
@series.route("/series/update/<id>", methods=["POST", "GET"])
def update(id):
    #Guardamos en un objeto serie con el id recibido
    serie = Serie.query.get(id)
    # Guardamos la lista de marcas
    marcas = Marca.query.all()
    # Si le llega como POST proceder al update
    if request.method == 'POST':
        # Recoger valores del formulario
        nombre = request.form["nombre"]
        valor = request.form["marca_id"]
        #Si el nombre no está vacío
        if (nombre != ""):
            # Si no ha introducido valor en la marca_id asignaremos el que tenía ya
            if(valor == 'None'):
                marca_id = serie.marca_id
            else:
                marca_id = valor        
            # Comprobar si existe ese registro  por nombre y por marca_id
            records = db.session.query(Serie).filter_by(nombre=nombre, marca_id=marca_id).first()
            #Comprobar si no está vacío
            if(records == None):
                # Aplicarle los cambios al objeto
                serie.nombre = nombre
                serie.marca_id = marca_id
                # Guardado de la session de la bbdd
                db.session.commit()
                # guardamos mensaje en la funcion flash
                flash("Serie updateado satisfactoriamente!")
                # Función de flask para hacer redirecciones 
                return redirect(url_for('series.index'))
            flash("Ese elemento ya existe!")    
    # Si llega como GET hará redirección a la vista de udpate con lo necesario
    return render_template('series/update.html', serie=serie, marcas=marcas)

# Función para eliminar un registro. Espera un id para hacer el delete
# Puede ser GET la primera vez que se ejecute para ir a la vista de confirmación de delete,
# Si se le da a SI en la vista de confirmación, entrará como método POST
@series.route("/series/delete/<id>", methods=["POST", "GET"])
def delete(id):
    # Guardamos el objeto que tenga ese id
    serie = Serie.query.get(id)
    # Si llega como POST se procede a la eliminación
    if request.method == 'POST':
        # Método delete de objeto de la bdd
        db.session.delete(serie)
        # Session commit para guardar los cambios
        db.session.commit()
        # Envio del mensaje al html
        flash("Serie borrado satisfactoriamente!")
        # Función para hacer redirección de flask
        return redirect(url_for('series.index'))
    # Si llega como GET hará la redirección a la vista de confirmar delete
    return render_template('series/delete.html', serie=serie)
    

templates/series/delete.html
{% extends 'layout.html' %}

{% block body %}

<h1 class="text-white">Delete Serie</h1>

<form  action="/series/delete/{{serie.id}}" method="POST" class="card p-2 bg-dark text-light w-50" style="margin: auto;">

    <div class="mb-3 text-center">
        <h2 id="marca">{{serie.marca}}</h2>
        <h2 class=" bg-white border-0 text-black" >{{serie.nombre}}</h2>

    </div>


    <h4 class="text-center"> ¿Seguro quieres borrar esta serie? </h4>

    <h5 class="m-3 text-center">Esta acción también borrará los vehiculos asociados a esta serie</h5>

    <button class="btn btn-primary bg-blue btn-sm rounded-pill" style="width: 100px; align-self: center;">SI</button>


    <a class="btn btn-danger btn-sm rounded-0 rounded-pill mt-2" style="width: 100px; align-self: center;" href="{{ url_for('series.index') }}">NO</a>

</form>

{% endblock %}

templates/series/index.html
{% extends 'layout.html' %}

{% block body %}

<script src="https://kit.fontawesome.com/2e7e2c30ba.js" crossorigin="anonymous"></script>

<link rel="stylesheet" href="/static/css/paginas_tablas.css">

<div class="row mt-2 justify-content-center">

    <div class="col-md-6 ">

        {% include 'partials/_message.html' %}

        <form action="/series/new" method="POST" class="card p-2 bg-dark text-light text-center ">

            <div class="MB-2 border ">
                <p class="align-self-center">CREAR SERIE</p>
            </div>

            <div class="mb-3 ">
                <label for="nombre text-center">Escribe nombre </label>
                <input class="form-control rounded-0 bg-dark border-0 text-white text-center" type="text" name="nombre" placeholder="Introduce nombre" />
            </div>

            <div class="mb-3 ">
                <label for="nombre">Elige la marca </label>
                <!-- <input class="form-control rounded-0 bg-dark border-0 text-white" type="text" name="nombre" placeholder="Introduce tu nombre" /> -->
                <select class="form-control text-center rounded-pill w-50" style="margin: auto;" name="marca_id" required>
                    {% for marca in marcas %}
                        <option value='{{marca.id}}'>{{marca.nombre}}</option>
                    {% endfor %}    
                </select>
            </div>
            
            <button class="btn-primary rounded-pill">Guardar</button>
            
        </form>
        
        <br>
          
    </div>

    <div class="col-md-12">
                
        <table class="table table-hover text-center table-dark">
            <tr>
                <th>Nombre Serie</th>
                <th>Marca</th>
                <th>Actualizar registro</th>
                <th>Borrar registro</th> 
            </tr>

        <!--MOTOR que usa Flask para esto es NINJA, usa formato liquid-->
        <!-- recorremos las series  -->
        {% for serie in series %}

            <tr>
                <td><span class="">{{serie.nombre}}</span> </td>
                <td><span>{{serie.marca}}</span></td>
                <td><a href="{{ url_for('series.update',  id=serie.id) }}"><i class="bg-primary text-dark fas fa-wrench"></i></a></td>
                <td><a  href="{{ url_for('series.delete',  id=serie.id) }}"><i class="fas fa-trash-alt bg-danger text-dark"></i></a></td>
            </tr>

        {% endfor %}

        </table>
  
    </div>

</div>

{% endblock %}

templates/series/update.html
{% extends 'layout.html' %}

{% block body %}

<h1 class="text-white">Update Serie</h1>

<form action="/series/update/{{serie.id}}" method="POST" class="card p-2 bg-dark text-light w-50" style="margin: auto;">

    {% include 'partials/_message.html' %}

    <div class="row">
        <div class="col">
            <div class="mb-3 text-center">
                <label for="nombre">Introduce nombre</label>
                <input class="form-control bg-white border-0 text-black text-center" type="text" name="nombre"
                    placeholder="Introduce tu nombre" value="{{serie.nombre}}" />

            </div>
        </div>
        <div class="col">
            <div class="mb-3 text-center">
                <label for="marca_id">Introduce Marca</label>
                <select class="form-control text-center" name="marca_id" required>
                    <option value="None" selected>Select an Option</option>
                    {% for marca in marcas %}
                    <option value='{{marca.id}}'>{{marca.nombre}}</option>
                    {% endfor %}
                </select>

            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col" style="margin-left: 35%;">
            <button class="btn btn-primary bg-blue btn-sm">Guardar </button>
            <a class="btn btn-danger btn-sm" style="height: 31px;" href="{{ url_for('series.index') }}">Cancelar</a>
        </div>
    </div>
</form>


{% endblock %}