models/vehiculo.py
# De util.db importa el db para pasarle el modelo.
from utils.db import db


class Vehiculo(db.Model):
    # opción de sqlalchemy para mejorar el motor de búsqueda.
    __searchable__ = ['matricula']
    id = db.Column(db.Integer, primary_key=True)
    matricula = db.Column(db.String(100))
    color = db.Column(db.String(100))
    # Especificamos que propiedad es la foreign key en la relación
    serie_id = db.Column(db.Integer, db.ForeignKey('serie.id'))

    def __init__(self, matricula, color):
        self.matricula = matricula
        self.color = color

    def __repr__(self):
        return f"Vehiculo ({self.matricula})"

    def __str__(self):
        return self.matricula

routes/vehiculo.py
#Imports de flask y componentes necesarios
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.serie import Serie
from models.vehiculo import Vehiculo
from utils.db import db

# Linea enroutador. Para llamarlo desde otras clases
vehiculos = Blueprint("vehiculos", __name__)

# Método que devuelve la vista de la lista de vehiculos 
@vehiculos.route("/vehiculos/")
def index():
    # Guarda el total de elementos en una variable de lista, y la lleva al template
    series = Serie.query.all()
    vehiculos = Vehiculo.query.all()
    return render_template("vehiculos/index.html", series=series, vehiculos= vehiculos)

# Método que se ejecuta cuando se guarda una nuevo vehiculo en la bbdd
@vehiculos.route("/vehiculos/new", methods=["POST"])
def add():
    # Con la función request de flask saca el valor  del form del template
    matricula = request.form["matricula"]
    color = request.form["color"]
    serie_id = request.form["serie_id"]
    # Comprobar si existe ese registro SOLO POR MATRICULA
    records = db.session.query(Vehiculo).filter_by(matricula=matricula).first()
    # Si no encuentra ninguno lo creará
    if records == None:
        # Comprobar si no está vacía la matricula
        if(matricula != ""):
            # Nuevo objeto para guardar
            new_vehiculo = Vehiculo(matricula, color)
            # añadirle a la serie el vehiculo que se ha creado   
            serie = Serie.query.get(serie_id)
            serie.vehiculos.append(new_vehiculo)
            # guardar el vehiculo en la bbdd
            db.session.add(new_vehiculo)
            # Ahora se acaba con la conexión y se hace commit
            db.session.commit()
            # Antes de reenviar, guardamos algo en la funcion flash
            flash("Vehículo añadido satisfactoriamente!")
            # Función de flask para hacer redirecciones 
            return redirect(url_for('vehiculos.index'))
        # Si está vacío no muestra mensaje y vuelve al index sin hacer nada
        return redirect(url_for('vehiculos.index')) 
    # Si ya existe indica el mensaje y vuele al index
    flash("Ese elemento ya existe")
    return redirect(url_for('vehiculos.index'))    


# Método que se acciona al escribir algo en el campo de búsqueda por matrícula de la vista
# Buscará ese elemento y devolverá como lista y si no devolverá uno vacío.
@vehiculos.route("/vehiculos/busqueda_matricula", methods=["POST"])
def search_matricula():
    # Recogemos la variable de matricula
    matricula2 = request.form["matricula2"]
    # Si no ha introducido nada en la búsqueda devuelve el index con todos vehiculos
    if matricula2 == '' :
        return redirect(url_for('vehiculos.index'))
    # Busqueda de elementos por la matricula.
    records = db.session.query(Vehiculo).filter_by(matricula=matricula2).first()
    #Cargamos todas las series también porque se necesita enviarse a la vista debido al formulario de creación y de busqueda por serie
    series = Serie.query.all()
    # Array para enviar según los resultados de "records"
    results = []
    # Si no está vacío lo añadirá al array. (Será de un sólo elemento siempre)
    if records != None:
        results.append(records)
    # Creamos una lista que siempre contiene todos los vehículos para el autocompletar de la vista
    vehiculos_total = Vehiculo.query.all()
    # Devuelve la vista del index con los vehiculos como el array results. Si está vacio pq no ha encontrado nada
    # lo gestionará la vista con un mensaje.
    return render_template("vehiculos/index.html", series=series, vehiculos= results, vehiculos_total=vehiculos_total)


# Método que se acciona al seleccionar algo en el campo de búsqueda por serie de la vista
# Buscará los registros que pertenezcan a esa serie y devolverá como lista.
@vehiculos.route("/vehiculos/busqueda_serie", methods=["POST"])
def search_serie():
    # Recogemos el objeto que coindice con el introducido del campo búsqueda
    serie_busqueda = request.form["serie_busqueda"]
    # Si no ha introducido nada en la búsqueda devuelve el index
    if serie_busqueda == 'None':
        return redirect(url_for('vehiculos.index'))
    # Busca los elementos que tengan esa serie_id
    records = db.session.query(Vehiculo).filter_by(serie_id=serie_busqueda).all()
    # Recogemos todas las series que hacen falta en la vista
    series = Serie.query.all()
    # Creamos una lista que siempre contiene todos los vehículos para el autocompletar de la vista
    vehiculos_total = Vehiculo.query.all()
    # Devuelve los vehiculos para el index con los que haya encontrado.
    return render_template("vehiculos/index.html", series=series, vehiculos= records, vehiculos_total=vehiculos_total)


# Función para eliminar un registro. Espera un id para hacer el delete
# Puede ser GET la primera vez que se ejecute para ir a la vista de confirmación de delete,
# Si se le da a SI en la vista de confirmación, entrará como método POST
@vehiculos.route("/vehiculos/delete/<id>", methods=["POST", "GET"])
def delete(id):
    # Guardamos el objeto que tenga ese id
    vehiculo = Vehiculo.query.get(id)
    # Si entra como método post
    if request.method == 'POST':
        # Se hace función eliminar de la bbdd de sqlalchemy
        db.session.delete(vehiculo)
        # Se guardan los cambios con commit de la bdd
        db.session.commit()
        # Devuelve mensaje a la vista y carga el index
        flash("Vehiculo borrado satisfactoriamente!")
        return redirect(url_for('vehiculos.index'))
    # Si entra como método GET devuelve la vista de confirmación de delete.
    return render_template('vehiculos/delete.html', vehiculo=vehiculo)


# Método para hacer un update de un elemento.
# Acepta los métodos de GET para llevar a la viste del update con el objeto,
# También el método POST cuando se haya ejecutado la opción de update del formulario.
@vehiculos.route("/vehiculos/update/<id>", methods=["POST", "GET"])
def update(id):
    #Guardamos en un objeto vehiculo con el id recibido
    vehiculo = Vehiculo.query.get(id)
    # Recogemos todas las series para mostrarla en la vista del update
    series = Serie.query.all()
    # Si entra como POST
    if request.method == 'POST':
        # Recoger valores del formulario
        matricula = request.form["matricula"]
        color = request.form["color"]
        valor = request.form["serie_id"]
        #Si el nombre no está vacío
        if (matricula != ""):
            # Si no ha introducido valor asignaremos el que tenía ya
            if(valor == 'None'):
                serie_id = vehiculo.serie_id
            else:
                serie_id = valor        
            # Comprobar si existe ese registro POR MATRICULA por si cambia
            records = db.session.query(Vehiculo).filter_by(matricula=matricula).first()
            # Si no existe ese registro o si que existe pero es el mismo que el del objeto
            # pasará a ejecutar el update
            if(records == None or records.id == int(id)):
                # Cambiamos los valores al objeto
                vehiculo.matricula = matricula
                vehiculo.color = color
                vehiculo.serie_id = int(serie_id)
                # Commit para guardar la bbdd
                db.session.commit()
                # mensaje a la vista con el elemento flash de flask
                flash("Vehiculo updateado satisfactoriamente!")
                # Devuelve la vista de index de nuevo 
                return redirect(url_for('vehiculos.index'))
            # si si existe lo muestra y sigue en la pantalla de update    
            flash("Ese elemento ya existe!")    
    # si entra como GET devuelve la vista con el update y el objeto 
    return render_template('vehiculos/update.html', series=series, vehiculo=vehiculo)

templates/vehiculos/delete.html
{% extends 'layout.html' %}

{% block body %}

<h1 class="text-white">Delete Vehiculo</h1>

<form  action="/vehiculos/delete/{{vehiculo.id}}" method="POST" class="card p-2 bg-dark text-light w-50" style="margin: auto;">

    <div class="mb-3">
        <h2 id="marca" align='center'>{{vehiculo.serie}}</h2>
        <h2 class="border-0" align='center'>{{vehiculo.matricula}}</h2>
        <h2 class="border-0" align='center'>{{vehiculo.color}}</h2>

    </div>


    <h3 align='center'> ¿Seguro quieres borrar el elemento? </h3>

    <button class="btn btn-primary bg-blue btn-sm rounded-0 rounded-pill mt-2" style="width: 100px; align-self: center;" >SI</button>


    <a class="btn btn-danger btn-sm rounded-0 rounded-pill mt-2" style="width: 100px; align-self: center;" href="{{ url_for('vehiculos.index') }}">NO</a>

</form>

{% endblock %}

templates/vehiculos/index.html
{% extends 'layout.html' %}

{% block body %}

<link href="/static/css/paginas_tablas.css" rel="stylesheet">


<script src="https://kit.fontawesome.com/2e7e2c30ba.js" crossorigin="anonymous"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js">  
</script>  

<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js">  
</script>  

<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css"
    rel="stylesheet" type="text/css" />  

<div class="row justify-content-center mt-3">

    <!-- empieza formulario -->
    <div class="col-3 mt-2">
        
        {% include 'partials/_message.html' %}

        <form action="/vehiculos/new" method="POST" class="card p-2 bg-dark text-light text-center">
            <div class="mb-3 border ">
                <p class="align-self-center">CREAR VEHÍCULO</p>
            </div>
            <div class="mb-3">
                <label for="matricula">Escribe la matrícula </label>
                <input class="form-control rounded-0 bg-dark border-0 text-white text-center rounded-pill" type="text" name="matricula" placeholder="Introduce matrícula" />
            </div>
            <div class="mb-3">
                <label for="color">Escribe el color </label>
                <input class="form-control rounded-0 bg-dark border-0 text-white text-center rounded-pill" type="text" name="color" placeholder="Introduce color" />
            </div>


            <div class="mb-3">
                <label for="nombre ">Elige la serie </label>
                <!-- <input class="form-control rounded-0 bg-dark border-0 text-white" type="text" name="nombre" placeholder="Introduce tu nombre" /> -->
                <select class="form-control text-center rounded-pill"  name="serie_id" required>
                    {% for serie in series %}
                        <option value='{{serie.id}}'>{{serie.nombre}} - {{serie.marca}} </option>
                    {% endfor %}    
                </select>
            </div>

           
          
            <button class="btn-primary rounded-pill">Guardar</button>
          </form>
    </div>

    <!-- empieza cuadros busqueda -->
    <div class="col-6 align-self-center">
        <form action="/vehiculos/busqueda_matricula" method="POST" class=" bg-ligth text-dark">
            <div class="mb-3 row cuadro_busqueda">
                <label for="matricula2"  class="col text-dark text-center align-self-center">Busqueda por matrícula </label>
                <input id="tags" class="form-control col text-black text-center rounded-pill" type="text" name="matricula2" placeholder="Introduce matrícula" />
                
                <button class="btn btn-secondary col-2 rounded-pill">Buscar</button>
            </div>
        </form>    

        <form action="/vehiculos/busqueda_serie" method="POST" class=" bg-ligth text-dark">
            <div class="mb-3 row cuadro_busqueda">
                <label for="serie_busqueda" class="col text-dark text-center align-self-center">Busqueda por tipo de serie </label>
                <select class="form-control col text-center rounded-pill"  name="serie_busqueda" required>
                    <option value="None" selected>Selecciona una serie</option>
                    {% for serie in series %}
                        <option value='{{serie.id}}'>{{serie.nombre}} - {{serie.marca}}</option>
                    {% endfor %}    
                </select>
                <button class="btn btn-secondary col-2 rounded-pill">Buscar</button>

            </div>

        </form>
    </div>

</div>

<!-- Empieza el listado de vehículos -->
<div class="row mt-2">
    
    {% if vehiculos|length > 0 %}
    <table class="table table-hover text-center table-dark">
        <tr>
            <th>Matrícula</th>
            <th>Color</th>
            <th>Serie</th>
            <th>Marca</th>
            <th>Modificar Registro</th>
            <th>Borrar Registro</th>
        </tr>
            <!--MOTOR que usa Flask para esto es NINJA, usa formato liquid-->
            {% for v in vehiculos %}

                <tr>
                    <td> <span class="">{{v.matricula}}</span> </td>


                    <td style="background-color:{{v.color}};"><span class="fondo text-dark"> {{v.color}}</span></td>

                    <td><span >{{v.serie}}</span></td>

                    <td><span  >{{v.serie.marca}}</span></td>

                    <td><a class="" href="{{ url_for('vehiculos.update',  id=v.id) }}"><i class="bg-primary text-dark fas fa-wrench"></i></a></td>

                    <td><a class="" href="{{ url_for('vehiculos.delete',  id=v.id) }}"><i class="fas fa-trash-alt bg-danger text-dark"></i></a></td>

                </tr>

            {% endfor %}

        {% else %}

            <div class="card mb-1 text-white bg-dark">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h5 class="text-white">No hay resultados</h5>
                    </div>
                </div>
            </div>

        {% endif %}

    </table>



</div>


<script>
    // Carga de javascript
    $( function() {
        var availableTags = [];

        //La primera vez que cargue el index no tiene esa variable de vehiculos total
        //entonces cargará las matrículas de la lista de vehiculos totales.
        //Una vez cargué en la vista según la búsqueda tendrá que recurrir a la
        //variable comodín que contiene todos los vehiculos.
        {% if vehiculos_total|length == 0 %}

            {% for v in vehiculos %}
                availableTags.push("{{v.matricula}}")
            {% endfor %}

        {% else %}

            {% for v in vehiculos_total %}
                availableTags.push("{{v.matricula}}")
            {% endfor %}

        {% endif %}
        
        console.log(availableTags);

        //elemento de la librería que hace el autocompeltado en el input que tenga ese id
        $( "#tags" ).autocomplete({
            source: availableTags
        });
    } );
</script>


{% endblock %}

templates/vehiculos/update.html
{% extends 'layout.html' %}

{% block body %}

<h1 class="text-white">Update Vehiculo</h1>

<form action="/vehiculos/update/{{vehiculo.id}}" method="POST" class="card p-2 bg-dark text-light w-25"
    style="margin: auto;">

    {% include 'partials/_message.html' %}


    <div class="mb-3">
        <h2 id="marca">{{vehiculo.serie}}</h2>

        <label for="matricula">Introduce matricula</label>
        <input class="form-control rounded-0 bg-white border-0 text-black" type="text" name="matricula"
            placeholder="Introduce matrícula" value="{{vehiculo.matricula}}" />

    </div>


    <div class="mb-3">

        <label for="color">Introduce color</label>
        <input class="form-control rounded-0 bg-white border-0 text-black" type="text" name="color"
            placeholder="Introduce color" value="{{vehiculo.color}}" />

    </div>

    <div class="mb-3">
        <label for="serie_id">Introduce serie</label>
        <select class="form-control" name="serie_id" required>
            <option value="None" selected>Select an Option</option>
            {% for serie in series %}
            <option value='{{serie.id}}'>{{serie.nombre}} - {{serie.marca}}</option>
            {% endfor %}
        </select>

    </div>

    <div class="row">
        <div class="col">
            <button class="btn btn-primary bg-blue btn-sm" style="width: 75px; margin-left: 70px;">Save</button>
            <a class="btn btn-danger btn-sm" style="width: 75px;" href="{{ url_for('vehiculos.index') }}">Cancel</a>
        </div>
    </div>
</form>

{% endblock %}